# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_ci_cd_app do
    api_key = app_store_connect_api_key(
      key_id: "RB29T6X9U5",
      issuer_id: "69a6de77-add8-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_RB29T6X9U5.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false, # optional but may be required if using match/sigh
    )
    
    cert(api_key: api_key)
    sigh(api_key: api_key, app_identifier: 'com.sangnguyen.StudyCICD')
    
    
    build_app(
      project: "StudyCICD.xcodeproj",
      configuration: "Debug",
      scheme: "StudyCICD",
      silent: true,
      clean: true,
      output_directory: "../Output", # Destination directory. Defaults to current directory.
      output_name: "StudyCICD.ipa", # specify the name of the .ipa file to generate (including file extension)
    )
  end
  
  desc "Description of what the lane does"
  lane :run_unittest do    
    run_tests(
      project: "StudyCICD.xcodeproj",
      configuration: "Debug",
      scheme: "StudyCICDTests",
      devices: ["iPhone 12 Pro Max"],
      code_coverage: true,
      output_directory: "../Output/Tests",
      derived_data_path: "../Output/Derived"
    )
  end
  
  desc "Description of what the lane does"
  lane :code_coverage do    
    sh "rm -rf ../Output/CodeCoverage"
    xcov(
      derived_data_path: "../Output/Derived",
      project: "StudyCICD.xcodeproj",
      configuration: "Debug",
      scheme: "StudyCICD",
      output_directory: "../Output/CodeCoverage",
      minimum_coverage_percentage: 50.0,
    )
  end
end
