# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_app do
    build_app(
      configuration: "Debug",
      scheme: "StudyCICD",
      silent: true,
      clean: true,
      output_directory: "../Output", # Destination directory. Defaults to current directory.
      output_name: "StudyCICD.ipa",       # specify the name of the .ipa file to generate (including file extension)
      sdk: "iOS 10.0"        # use SDK as the name or path of the base SDK when building the project.
    )
  end
end
